### ISSUE TITLE
More events

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/choo-service-worker#3]
Not sure if it would be good idea to add more events to e.g. check when the sw has been updated or become redundant.

Check [this code](https://github.com/GoogleChrome/sw-precache/blob/7b1b4f84c69fb7ae88d03b66e6a97be7955f0f79/demo/app/js/service-worker-registration.js#L29-L60) for more details

**Comment by yoshuawuyts** [comment]
Yeah, that'd be very useful! PRs welcome!

**Comment by YerkoPalma** [comment]
PR on #4 :+1:

**Comment by YerkoPalma** [comment]
Merged, thanks :heart:
