### ISSUE TITLE
Module scope

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/choo-service-worker#5]
I was wondering what is the scope of this package. I want to add some features to the `choo-service-worker` plugin.

**For [navigationPreload](https://developers.google.com/web/updates/2017/02/navigation-preload)** 

```js
state.navigationPreloadSupported // bool - availaible after sw registration

emit('sw:enablePreload')         // Enable navigationPreload
emit('sw:disablePreload')        // Disable navigationPreload 
emit('sw:togglePreload')         // Toggle navigationPreload (might not be necesary)
```

**For [message posting](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage)**

```js
emit('sw:postMessage', data)     // Post an object to the registered service worker
on('sw:message', cb(message))    // Get a message sent from a worker. 
                                 // message is an object with 3 properties:
                                 //     - data: The content sent
                                 //     - channel: The channel where the message came front
                                 //     - data: The port, if any
```

**For [backgroundSync](https://developers.google.com/web/updates/2015/12/background-sync)**

```js
state.syncTags                   // Array - tags registered for background sync
emit('sw:sync', tag)             // Register a background sync event with a given tag
```

**For [notifications](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification)**

```js
emit('sw:notificationRequest', result)   // Request permissions for notifications
```

This might seem like a lot, but there is basically some _choo way_ wrappers around some of the [jakearchivald demos](https://github.com/jakearchibald/isserviceworkerready/tree/master/src/demos).

So, I'm not sure if is in the scope of this package to add those functionallities, or should I make some `choo-service-worker-helper` module or something. Since this module refer to service-workers, I think is better to keep all in the same place, but I'm ok also with making a new package. Is up to you :)

**Comment by yoshuawuyts** [comment]
Oh, I like this! Thanks for taking your time to write this out; it's so easy to review. PR very welcome!
