### ISSUE TITLE
navigation preload

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/choo-service-worker#7]
To speed up loading service workers, we can make use of `navigation preload`. But only conditionally, because it's not available everywhere yet. Can shave up to half a second from mobile service worker loads!

https://developers.google.com/web/updates/2017/02/navigation-preload

**Comment by yoshuawuyts** [comment]
Will be addressed by https://github.com/choojs/choo-service-worker/pull/6

**Comment by YerkoPalma** [comment]
Closed by #6
